name: Code quality

on:
  pull_request:
    branches: [
      master
    ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  code-quality:
    name: Code quality
    runs-on: ubuntu-latest
    steps:
    - name: Git checkout
      uses: actions/checkout@v3
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version-file: '.nvmrc'
    - name: Install
      run: npm ci
    - name: Build
      run: npm run build
    - name: Lint
      run: npm run lint
    - name: Test
      run: npm run test:ci
      env:
        NODE_OPTIONS: "--max_old_space_size=4096"
